# Generated by Django 5.2.4 on 2025-08-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tempuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='api_user',
        ),
    ]
