# Generated by Django 5.2.4 on 2025-08-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_tempuser_email_tempuser_email_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tempuser',
            name='email_idx',
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
