# # Generated by Django 5.2.4 on 2025-08-20 03:14

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [

#     ]

#     operations = [
#         migrations.AddField(
#             model_name='tempuser',
#             name='raw_password',
#             field=models.CharField(max_length=128, null=True),
#         ),
#     ]





from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
                ('api', '0007_remove_tempuser_email_idx_alter_tempuser_email_and_more'),
    ]
    operations = [
        migrations.AlterField(
            model_name='tempUser',
            name='raw_password',
            field=models.CharField(max_length=128),
        ),
    ]
